name:                 selfish-gen
version:              0.1.0.0
visibility:           public
id:                   selfish-gen-0.1.0.0-inplace
key:                  selfish-gen-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           tokareva_todal@mail.ru
author:               Алиса Токарева
abi:                  inplace
exposed:              True
exposed-modules:      Evolution Fitness Genetic Hello Phenotype Types
import-dirs:
    /home/alisa_unix/selfish_gen/dist-newstyle/build/x86_64-linux/ghc-9.14.1/selfish-gen-0.1.0.0/build

library-dirs:
    /home/alisa_unix/selfish_gen/dist-newstyle/build/x86_64-linux/ghc-9.14.1/selfish-gen-0.1.0.0/build

library-dirs-static:
    /home/alisa_unix/selfish_gen/dist-newstyle/build/x86_64-linux/ghc-9.14.1/selfish-gen-0.1.0.0/build

dynamic-library-dirs:
    /home/alisa_unix/selfish_gen/dist-newstyle/build/x86_64-linux/ghc-9.14.1/selfish-gen-0.1.0.0/build

data-dir:             /home/alisa_unix/selfish_gen/.
hs-libraries:         HSselfish-gen-0.1.0.0-inplace
depends:
    JuicyPixels-3.3.9-4b6642d505515290ca0998dc642ef1286273a9939359f905c50e23a51f56e90c
    base-4.22.0.0-fde1 directory-1.3.10.0-f140 filepath-1.5.4.0-71b0
    juicy-draw-0.2.0.0-0fff049847d173d8e657e5156f8b59b77448035fd00ff16def1b1f784afe8ee4
    primitive-0.9.1.0-1e5ccb4f3a3ef570efe06bd3c8472f799356a7a60f65f8156d45d2182401a4f5
    random-1.2.1.3-b51a0f9bd6e53f10d12e967a3cb206413d8d5b0942dfeec2cced024586e00ce8
    repa-3.4.2.0-dd8b31911d6693fd8d41f86b721efafb68f919d44ba780e7864056c41c4c77c4
    split-0.2.5-6355594979c2caa3d4f4565a4282492c47375528139bc91dc765f0d38b3867a2
    vector-0.13.2.0-32b53438c965f2ce4e5c110536f6717c303e59d49f5d3d5968abbb90ddf849e8

haddock-interfaces:
    /home/alisa_unix/selfish_gen/dist-newstyle/build/x86_64-linux/ghc-9.14.1/selfish-gen-0.1.0.0/doc/html/selfish-gen/selfish-gen.haddock

haddock-html:
    /home/alisa_unix/selfish_gen/dist-newstyle/build/x86_64-linux/ghc-9.14.1/selfish-gen-0.1.0.0/doc/html/selfish-gen
